### ISSUE TITLE
Encountered an error while following the instructions in the README. Please help.

### ISSUE THREAD

**Issue by Zhihui-SJTU** [ZHANG-Qidi/VCD2SAIF#1]
First, I would like to ask if my understanding is correct that the source code has been packaged into a Lisp environment, and is there a possibility of the source code being open-sourced?

The following is the terminal output log.
This is SBCL 2.3.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (load "vcd2saif_v1.2.lisp")
T
* (use-package 'package_vcd2saif)
T
* (vcd2saif "aes_enc_t_test.vcd" :simulation_time 239190000 :split_interval 10000 :tcl_count 4)

debugger invoked on a FILE-DOES-NOT-EXIST in thread
#<THREAD "main thread" RUNNING {1004490113}>:
  The file #P"/workspace/github/VCD2SAIF/aes_enc_t_test\\.vcd"
  does not exist:
    No such file or directory

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CREATE   ] Reopen with :if-does-not-exist :create
  1: [CONTINUE ] Retry opening.
  2: [USE-VALUE] Try opening a different file.
  3: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::FILE-PERROR #P"/workspace/github/VCD2SAIF/aes_enc_t_test\\.vcd" 2 FILE-DOES-NOT-EXIST)
0] (SB-EXT:EXIT)

**Comment by ZHANG-Qidi** [comment]
报错找不到 aes_enc_t_test.vcd 这个文件
VCD 文件是跑 Vivado 仿真时通过在测试脚本中插入VCD文件输出命令实现的.
https://github.com/ZHANG-Qidi/VCD2SAIF/blob/main/Examples/aes/Vivado/aes_vivado/aes_vivado.srcs/sim_1/new/aes.v
第52行
`initial begin : dump_vcd
    $dumpfile("aes.vcd");
    $dumpvars(0, aes.UUT);
end
`
例子里有已经生成的VCD文件
https://github.com/ZHANG-Qidi/VCD2SAIF/blob/main/Examples/aes/Vivado/aes_vivado/aes_vivado.sim/sim_1/impl/timing/xsim/aes.vcd
可以下载这个文件并替换命令中的 aes_enc_t_test.vcd 为 aes.vcd

**Comment by Zhihui-SJTU** [comment]
谢谢，问题已经解决了。
